### ISSUE TITLE
Request - >=TF2.3.0, CPU Westmere(no avx), Compute 6.1 Cuda 10.1, cudnn 7.6.5, ubuntu 18.04

### ISSUE THREAD

**Issue by Atrocks** [davidenunes/tensorflow-wheels#17]
got stuck building this configuration due to missing avx and/or cublas10 - problem - so reaching out to you, thanks for your time looking if you can support.
Unfortually due to shared server ubuntu, cuda and cudnn are fixed.

**Comment by davidenunes** [comment]
if you can get me a docker image with your target system requirements perhaps I can give it a try

Otherwise, if it helps:

set the `-march ` option to match your CPU like `bazel build -c opt --copt=-march=westmere`
missing cublas 10 seems like cuda is not installed properly or cannot be found in the path you provided

**Comment by Atrocks** [comment]
Thanks the cpu seems to be now detected - still error on some missing cuda files (gladfully not alone https://forums.developer.nvidia.com/t/cublas-for-10-1-is-missing/71015/4) took me some time finding the problem  - not very into symlinks and what is all missing - seems tobe something for a weekend

**Comment by davidenunes** [comment]
I'm closing this for now since I don't have time to put together a docker image to build to your specifications. If you need help with anything else feel free to re-open the issue.
