### ISSUE TITLE
TF 2.x python 3.7

### ISSUE THREAD

**Issue by arita37** [davidenunes/tensorflow-wheels#20]
Hello,
Thanks for your page.

would it be possible to build for
centos 7.2
TF 2.4
AVX

can sponsor for this.

thanks vm.

**Comment by davidenunes** [comment]
I would probably need to spin a VM for the build, since I'm using Arch but perhaps I can help you, 
I need more information though

Does the official install not work for your particular setup? I'm asking this 
because the official Tensorflow is built with oneAPI (with AVX support) 
since version 2.4

If this is not the case what problem are you encountering?
is it a library linking problem due to CentOS 7.2?
Do you have a particular CPU microarchitecture you want to build for?

Do you want the build for CUDA as well or just CPU
if so, which version of CUDA, cuDNN, NCCL, etc

**Comment by arita37** [comment]
Am too busy to fix 100s other issues….

Only CPU build for AVX, Xeon processors.
on CentOSz

Currently have the anaconda TF 2.6
and it says not compiled for AVX.

Thanks very much.

**Comment by arita37** [comment]
CPU is  Xeon Gold 6148

AVX512f,…. available

**Comment by davidenunes** [comment]
OK thanks, I was asking because I'm on a skylake if I don't specify anything it would target my architecture
it seems that **-march=skylake-avx512** should work for the [Xeon Gold 6148](https://en.wikichip.org/wiki/intel/xeon_gold/6148). I'll see what I can do.

**Comment by arita37** [comment]
Thanks you for prompt.
Am sorry, am just too busy to fix 100s
other issues…. (not related to TF).

TF CPU only 2.6
Python 3.7
CentOS 7.2
Xeon Gold 
https://en.wikichip.org/wiki/intel/xeon_gold/6148

Think it’s skylake.

Thanks in advance for the help,
Happy to sponsor you.

**Comment by arita37** [comment]
Hello,

Sorry, this seeems the
Tf 2.6 anaconda is optimized ofr oneAPI with AVX512

Got some mis read of the log message.
Sorry, for the burden.

**Comment by davidenunes** [comment]
That's why I asked if there was other problem preventing you from using the official install
I thought it could be something OS-related.

So everything works? 

I ended-up building it last night, so you can test it if you want
[https://github.com/davidenunes/tensorflow-wheels/releases/tag/r2.6.1.cp37.avx512f](https://github.com/davidenunes/tensorflow-wheels/releases/tag/r2.6.1.cp37.avx512f)

but oh well

**Comment by arita37** [comment]
Thanks so much….

If you visit Japan, feel free to reach,
Happy to help.
