### ISSUE TITLE
2.0 Build for Ubuntu

### ISSUE THREAD

**Issue by jzalger** [davidenunes/tensorflow-wheels#6]
Hey David, any way you can do the following build on Ubuntu 19?
2.0 | GPU | 3.7 | 10.1 | 7.6 | XLA,SSE,AVX,FMA

I am struggling building it from source on my machine.

**Comment by davidenunes** [comment]
I don't have any image for Ubuntu 19 ready to go, so it would take me a bit more time since I need to set that up first (if you have a docker image with all the tools, CUDA, etc, that would help). If I get some time, I'll give it a try and let you know. Since you want the SSE AVX FMA instructions, what's your processor march? I'm on a skylake, it that causes no problems I can just build for my native hardware.

**Comment by jzalger** [comment]
I have a Sandybridge chip, has AVX but not AVX2.
I am on Ubuntu 19.10.

I have never used docker actually, but I can give it a try this week.

Its weird that the internet does not have a build wheel for that configuration on Ubuntu...

**Comment by davidenunes** [comment]
closing this, because I didn't have the time back then and a couple of releases came out recently
